---
name: Main

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEB_SITE_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Test
        run: |
          npm ci
          npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Lint
        run: |
          npm ci
          npm run lint

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Check
        run: |
          npm ci
          npm run check

  deploy-studio-graphql:
    runs-on: ubuntu-latest
    needs: [test, lint, check]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Deploy Studio Graphql Server
        run: |
          npm ci
          npx sanity graphql deploy --no-playground --force
        working-directory: ./studio

  deploy-web:
    runs-on: ubuntu-latest
    needs: [deploy-studio-graphql]
    if: "!contains(github.event.head_commit.message, '[skip netlify]')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Deploy Website
        run: |
          npm ci
          netlify build --context production
          netlify deploy --prod --message "${{ github.event.head_commit.message }}"
        working-directory: ./web
