---
name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v2

      - run:
          - npm ci
          - npm test

  lint:
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v2

      - run:
          - npm ci
          - npm run lint

  deploy-graphql:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/master'
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Graphql Server
        run:
          - npm ci
          - npm run graphql-deploy
        working-directory: ./studio
