---
name: Main

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEB_SITE_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Test
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Lint
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yarn lint

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Check
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yarn run check

  deploy-studio-graphql:
    runs-on: ubuntu-latest
    needs: [test, lint, check]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Deploy Studio Graphql Server
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yarn sanity graphql deploy --no-playground --force --dataset production
        working-directory: ./studio

  deploy-web:
    runs-on: ubuntu-latest
    needs: [deploy-studio-graphql]
    if: "!contains(github.event.head_commit.message, '[skip netlify]')"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Deploy Website
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          netlify build --context production
          netlify deploy --prod --message "${{ github.event.head_commit.message }}"
        working-directory: ./web
