---
name: Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Test
        run: |
          npm ci
          npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Lint
        run: |
          npm ci
          npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Build
        run: |
          npm ci
          npm run build

  deploy-graphql:
    runs-on: ubuntu-latest
    needs: [test, lint]
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      GATSBY_SANITY_TAG: pr-${{ github.event.number }}
      GATSBY_SANITY_DATASET: development

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Deploy Graphql Server
        run: |
          npm ci
          npx sanity graphql deploy --no-playground --tag "$GATSBY_SANITY_TAG" --dataset "$GATSBY_SANITY_DATASET"
        working-directory: ./studio
