---
name: Pull Request Closed

on:
  pull_request:
    types: [closed]

env:
  GATSBY_SANITY_DATASET: development
  GATSBY_SANITY_TAG: pull-request-${{ github.event.pull_request.number }}
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}

jobs:
  deploy-studio-graphql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Deploy Studio Graphql Server
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          npx sanity graphql deploy --no-playground --dataset development
        working-directory: ./studio

  remove-studio-graphql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Undeploy Studio Graphql Server
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yes | yarn sanity graphql undeploy --tag "$GATSBY_SANITY_TAG" --dataset "$GATSBY_SANITY_DATASET"
        working-directory: ./studio
