---
name: Pull Request

on: [pull_request]

env:
  GATSBY_SANITY_DATASET: development
  GATSBY_SANITY_TAG: pull-request-${{ github.event.pull_request.number }}
  GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEB_SITE_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Test
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Lint
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yarn lint

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Check
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yarn run check

  deploy-studio-graphql:
    runs-on: ubuntu-latest
    needs: [test, lint, check]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Deploy Studio Graphql Server
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          yarn sanity graphql deploy --no-playground --tag "$GATSBY_SANITY_TAG" --dataset "$GATSBY_SANITY_DATASET"
        working-directory: ./studio

  deploy-web:
    runs-on: ubuntu-latest
    needs: [deploy-studio-graphql]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Deploy Website
        run: |
          yarn install --prefer-offline --frozen-lockfile --non-interactive
          netlify build --context deploy-preview
          netlify deploy --message "${{ env.GITHUB_PULL_REQUEST_TITLE }}" --alias "pull-request-${{ env.GITHUB_PULL_REQUEST_NUMBER }}"
        working-directory: ./web

      - name: Comment Preview URL
        uses: unsplash/comment-on-pr@master
        with:
          msg: "Deploy preview URL: https://pull-request-${{ env.GITHUB_PULL_REQUEST_NUMBER }}--bluebird-cabinetry-and-design.netlify.app/"
          check_for_duplicate_msg: true
