[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[build.environment]
  GATSBY_SANITY_PROJECT_ID="5sj6awst"

[context.production.environment]
  GATSBY_SANITY_DATASET="production"

[context.deploy-preview.environment]
  GATSBY_SANITY_DATASET="development"

[context.branch-deploy.environment]
  GATSBY_SANITY_DATASET="development"

